### ISSUE TITLE
Flickr Plugin

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#1]
For the [photos page](http://tinkersoc.org/photos.html)

**Comment by graymalkin** [comment]
Any suggestions on this? I might abandon the idea of a flickr plugin, otherwise.

**Comment by egelmex** [comment]
This was mostly done to reduce our hosting costs, and to make it easy to update, but it is viewed so rarely that it hasn't been an issue with costs, and no one has updated the fliker either. Make a script that generates a gallery from a folder full of photos instead?

**Comment by willfurnell** [comment]
Closing as there isn't currently a photos page.
