### ISSUE TITLE
Committee Page

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#10]
Pull the committee page over. Currently the committee is described in [a json document](https://github.com/TinkerSoc/TinkerWeb/blob/e5703e2674596c0e1b56ac029b9c2710b369e78e/_data/committee.json). It'd be nice to keep this as the json document, just because it seems like a sane way to store this data.

**Comment by sigwinch28** [comment]
TOML document per person in `data/committee/name.toml`. Automatically populates the incumbent members, founders, and all past members. Probably need a more elegant way to deal with the images, though.
