### ISSUE TITLE
Photos page

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#11]
This obviously ties in with the flickr plugin ( #1 )

**Comment by egelmex** [comment]
Would it be a good idea to unlink this page instead of having a blank page?

**Comment by egelmex** [comment]
@willfurnell as your fixing stuff can you unlink this page for now?

**Comment by willfurnell** [comment]
Yes can do, or link straight to the Facebook page photos?

**Comment by egelmex** [comment]
I don't think a main nav link should navigate away from the site personally.

**Comment by willfurnell** [comment]
The photos page has been removed.
