### ISSUE TITLE
Resources Pages

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#12]
We have a variety of Resources pages, some of these might need review anyway, so for now I'll keep this as an umbrella issue, which we can branch out into others.

**Comment by sigwinch28** [comment]
Got the committee page done, but the others will probably need some TLC

**Comment by graymalkin** [comment]
Mostly ported with dfff01a7a5ecaa4142f3eedcdfb43978d14fa290 3fb855930c9994e7c85d6b5a31620d36c91337b6 44719ff88472e429b385fd7ede6687114f170416 892d607634dd7dba73a79bfc292c8acf5bf33c09 d0867f23b94e20d8d28e78d8d1401984d48e8219
