### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#13]
We have a very simple calendar page at the moment which simply embeds a google calendar. This is probably adequate.

We might be able to do better though, so consider other options before closing this with a straight duplication of what currently exists.

**Comment by Tatskaari** [comment]
At the very least replace the fake loading bar with a spinner.

**Comment by graymalkin** [comment]
Closed with 76a1b13eca5a21f88581deec29be1325803599e3.
