### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by sigwinch28** [TinkerSoc/TinkerWeb#14]
Re-create the old theme using Hugo's helper functions and proper partials instead of a straight jekyll port

**Comment by graymalkin** [comment]
Probably sensible, I'm hacking about with the themes as they currently exist and they're not really suitable

**Comment by sigwinch28** [comment]
Only the footer left now, really.

**Comment by graymalkin** [comment]
Mostly happy with the theme now. We might want to change the accent colour. Should all be idiomatic.
