### ISSUE TITLE
Add CSP headers / meta tag

### ISSUE THREAD

**Issue by egelmex** [TinkerSoc/TinkerWeb#15]
http://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by graymalkin** [comment]
I fucked the calendar with this. Need to whitelist google calendar.

**Comment by willfurnell** [comment]
The calendar appears to work for me on Firefox, Chrome and Safari. The resources do have some CSP problems though. Will whitelist those domains.

**Comment by graymalkin** [comment]
Yeah you're quite right. The google docs things don't appear to be working though, like the [constitution](http://www.tinkersoc.org/resources/constitution/), and [general meeting minutes](http://www.tinkersoc.org/resources/general-meeting-minutes/).

**Comment by willfurnell** [comment]
https://github.com/TinkerSoc/TinkerWeb/commit/e331a237f55d2775739c8a4c339c05e48d8cad06 should hopefully fix this. Do I need to merge my changes to live/deploy at all?
Thanks.

**Comment by graymalkin** [comment]
Looks good. I think if I merge it into one of the branches it'll update the website automagically.
