### ISSUE TITLE
Content for footer

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#16]
No idea what to put on the RHS of the footer.

**Comment by egelmex** [comment]
Can we bring back upcoming events?

**Comment by berry120** [comment]
I'd be tempted to go for a much smaller footer, perhaps just with the social media links as icons spaced horizontally (and nothing else?)

**Comment by egelmex** [comment]
> I'd be tempted to go for a much smaller footer, perhaps just with the social media links as icons spaced horizontally (and nothing else?)

Doesn't sound like a bad option to me.

**Comment by willfurnell** [comment]
I've made this change in https://github.com/TinkerSoc/TinkerWeb/commit/45c07cae65d19aff86f4c431a52cdde973b0e7ed. Flickr was removed because there haven't been any new photos in 4 years - but this can be added in.
