### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#20]
We can use aliases to support redirecting old links like `http://www.tinkersoc.org/resources/radio.html` to the new `http://www.tinkersoc.org/resources/radio/`

**Comment by graymalkin** [comment]
Is this necessary?

**Comment by egelmex** [comment]
It would have been good when the site was made, as we were still getting a lot of traffic from hackaday. Not sure it's worth it now?
