### ISSUE TITLE
Committe images don't line up

### ISSUE THREAD

**Issue by berry120** [TinkerSoc/TinkerWeb#21]
The images for the committe don't quite line up at present - probably easy to fix just by manually tweaking the images to be the same size.
![unbalanced](https://cloud.githubusercontent.com/assets/7595149/18962540/2cd28b16-8669-11e6-8d70-7831ea27ceb0.png)

**Comment by graymalkin** [comment]
@sigwinch28 said he fancied having a go at this.

**Comment by graymalkin** [comment]
Fixed by ad860a07179ecf397e0d41a39eb20316280ff8ca
