### ISSUE TITLE
All the content is bellow the fold.

### ISSUE THREAD

**Issue by egelmex** [TinkerSoc/TinkerWeb#22]
Content on the home page is all bellow the fold. Add a something to make it clear there is more content, possibly a down chevron at the bottom of the video.

![image](https://cloud.githubusercontent.com/assets/474014/18962543/3164e4ee-8669-11e6-8b3e-988f5c05e12a.png)

Solution (Like this only less terrible)

![image](https://cloud.githubusercontent.com/assets/474014/18962585/5ee57780-8669-11e6-92a8-79d50b063375.png)

**Comment by willfurnell** [comment]
I've just made a commit for this - but it doesn't look centered at the moment - not sure how to do this without hacking it by moving it by -N pixels.

**Comment by egelmex** [comment]
On my screen the arrow is still below the fold. Might need to make it an
overlay like a sticky footer.[image: image.png]
