### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by egelmex** [TinkerSoc/TinkerWeb#23]
Copyright notice isn't needed, but if we keep it I think it should be reduce in size so it doesn't weigh equally with the content in the footer above it.

![image](https://cloud.githubusercontent.com/assets/474014/18962755/fe12bb88-8669-11e6-9087-4246aa3492ff.png)

**Comment by graymalkin** [comment]
This should be sorted out with #16

**Comment by egelmex** [comment]
I think this ticket should still be open, I see the date got fixed which is nice but do we need the notice at all? and it's still way to big on comparison with teh content around it.

**Comment by egelmex** [comment]
![image](https://user-images.githubusercontent.com/474014/29464783-e127daa8-842e-11e7-88f6-0ccc9ad92df8.png)

If we do keep it somethign like this would be better I think.

**Comment by willfurnell** [comment]
It does look better without it at all - is copyright on the content implicit anyway?

**Comment by egelmex** [comment]
Yes I believe so.

**Comment by graymalkin** [comment]
This was fixed with c5b6bfd94c396c63f97a89323d1507f8c8aec551 and 4ebd3d9bb990022480c4e1989e862eccbb36089a
