### ISSUE TITLE
Logo unclear on my PC

### ISSUE THREAD

**Issue by egelmex** [TinkerSoc/TinkerWeb#27]
Logo is a little small and unclear on my browser.

![image](https://cloud.githubusercontent.com/assets/474014/18993733/92a50b2c-871c-11e6-95c7-a1210ac039c2.png)

**Comment by graymalkin** [comment]
tough

**Comment by egelmex** [comment]
No this is an issue. It's the only place the logo shows on the site at the moment.

**Comment by Tatskaari** [comment]
There should be a vector graphic around from when we made the key rings.

**Comment by graymalkin** [comment]
It is an SVG

**Comment by willfurnell** [comment]
@egelmex is this still an issue for you?

**Comment by egelmex** [comment]
OK on this PC, close it, I will re-open if I see it looking rubbish
somewhere else
