### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#4]
We'll need to work out how to do pagination and infinite scrolling with Hugo.

It might all be supported out-of-the-box, but we'll need to migrate from our old system.

**Comment by egelmex** [comment]
I would be happy to remove the infinite scroll, it's not great for
accessibility anyway.

**Comment by sigwinch28** [comment]
If we throw infinite scrolling out the window, Hugo has inbuild support for pagination. That, and bootstrap has some pretty nice elements for pagination we can tack on the end of list pages.
