### ISSUE TITLE
Wording on Join-Us page

### ISSUE THREAD

**Issue by egelmex** [TinkerSoc/TinkerWeb#42]
Proposed change to Join-Us page to make it clearer, fix capitalisation, and remove ambiguities.

Current:

> The membership for the whole year is **Free for School of Computing Students, £10 for all other Kent Students, and £13 for non-students**. This membership fee covers many of our events entirely, including all of the talks. However, we may need to charge for certain kits and materials required to participate in workshops. Don’t worry though, we will make sure you know this well in advance and will try to keep the price for one workshop under £5 where possible.

Proposed Change:
> The annual membership fee is:
> * School of Computing Students: **Free**
> * Other Kent Students: **£10**
> * Associate Members: **£13**
>
> This membership fee covers the large majority of our events, including all of the talks. However, we may need to charge for certain kits and materials required to participate in workshops. Don’t worry though, we will make sure you know this well in advance and will try to keep the price for one workshop under £5 where possible.

**Comment by graymalkin** [comment]
This would be better. Emphasising the _free_ part would also be nice. I prefer prices to be up-front and clear, so they should be out of line from body text.

**Comment by egelmex** [comment]
How about that (updated above)

**Comment by danielknox** [comment]
I would suggest 'The membership for the whole year is:'  should be 'The annual membership fee is:'.
Otherwise looks good

**Comment by egelmex** [comment]
Yeah that sounds better.

**Comment by willfurnell** [comment]
Fixed in https://github.com/TinkerSoc/TinkerWeb/pull/43
