### ISSUE TITLE
Why is master not the live branch?

### ISSUE THREAD

**Issue by willfurnell** [TinkerSoc/TinkerWeb#54]
Just wondering - why is master not used as the branch which is shown on the (non-staging) site?

Pull requests are needed to make changes to master anyway, so code/content reviews do take place at least once before they are shown live, rather than needing two pull requests to make a change to the site.

**Comment by graymalkin** [comment]
There's a fee for uploading to AWS, so master gives a place for good changes from feature branches to be accumulated before pushing them live.

**Comment by egelmex** [comment]
It also gives us a second point to check for errors before going live.

**Comment by willfurnell** [comment]
@graymalkin That's a fair reason.
