### ISSUE TITLE
Youtube Plugin

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#6]
We have a plugin to generate the HTML required for embedding youtube videos. A plugin is nice for this, as it keeps it consistent throughout the site, and we can automatically put the youtube videos in a wrapper which we have more control, when compared to the default output of the "Embed" option on YouTube.

**Comment by Tatskaari** [comment]
There's already a shortcode for youtube. Does the suffice? https://gohugo.io/extras/shortcodes/

**Comment by graymalkin** [comment]
Might well do, it would at least be consistent.

**Comment by sigwinch28** [comment]
The shortcode does the job better. If it doesn't, it's only a custom shortcode away to play nice with bootstrap.
