### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by graymalkin** [TinkerSoc/TinkerWeb#9]
Recreate the blog index and sub-pages. Particularly important is keeping URLs compatible

**Comment by egelmex** [comment]
Agreed, all current URLs should still point to the data, or redirect to the
new location of the data.

**Comment by graymalkin** [comment]
Hugo takes the same permalink format as Jekyll in the config.yaml

**Comment by graymalkin** [comment]
Got the blog rendered the same as the old site with 8955662f138f0053b63967d06ab2e5f3116f4f8c

Just need to sort out:
- [x] Post Dates
- [x] Permalink format
- [ ] Pagination
- [ ] Archives

**Comment by graymalkin** [comment]
Not sure if I'll do pagination. Probably won't do archives, I don't think the blog is "browsed" enough to justify them.

**Comment by egelmex** [comment]
> Not sure if I'll do pagination. Probably won't do archives, I don't think the blog is "browsed" enough to justify them.

I agree that that archives/topics probably not needed for initial release.
